#HTTP Server
[server]
    address = ":8199"
    serverRoot = "public"
    serverAgent = "go_web"
    logPath = "./log/server"
    nameToUriType = 2
    routeOverWrite = true

[logger]
    path = "./log"
    level = "all"
    stdout = true

# Template view configurations.
[viewer]
    path = "template"
    defaultFile = "index.html"

# Database configurations.
[database]
    link = "mysql:root:root@tcp(127.0.0.1:3306)/test"
    debug = true
    # 数据库日志对象配置
    [database.logger]
        Path = "./log/sql"
        Level = "all"
        Stdout  = true




