#HTTP Server
[server]
    address = ":8199"
    serverRoot = "public"
    serverAgent = "go_web"
    logPath = "./log/server"
    nameToUriType = 2
    routeOverWrite = true

[logger]
    path = "./log"
    level = "all"
    stdout = true

# Template view configurations.
# [viewer]
#     path = "template"
#     defaultFile = "index.html"

# Database configurations.
[database]
    link = "mysql:root:root@tcp(127.0.0.1:3306)/test"
    debug = true
    # 数据库日志对象配置
    [database.logger]
        path = "./log/sql"
        level = "all"
        stdout  = true
[redis]
    default = "127.0.0.1:6379,0"
    cache = "127.0.0.1:6379,0?idleTimeout=600"




